version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/breezewiki/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/iperf3/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/overviewer/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/overviewer-clone/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/sonic/"
    schedule:
      interval: "daily"