name: BreezeWiki - Build & Push

on:
  push:
    branches:
      - "main"
    paths:
      - "breezewiki/**"
      - ".github/workflows/breezewiki.yml"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  hadolint:
    name: ğŸ§ªRun hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: ğŸ¯ Checkout code
        uses: actions/checkout@v3

      - name: ğŸRun hadolint
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: ./breezewiki/Dockerfile
          format: sarif
          ignore: DL3008
          output-file: hadolint-results.sarif
          no-fail: true

      - name: âš¡Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ¯ Check Out Repo
        uses: actions/checkout@v3

      - name: ğŸ‘·â€â™€ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ™ Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ‹Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ‘·â€â™‚ï¸ğŸ‹ğŸ‘·â€â™€ï¸ Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: breezewiki/.
          file: Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x
          labels: |
            org.opencontainers.image.source=https://github.com/Zottelchen/docker-container
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=BreezeWiki is a simple wiki front written in Racket.
          push: true
          cache-from: gha
          cache-to: gha
          tags: |
            zottelchen/breezewiki:latest
            ghcr.io/zottelchen/breezewiki:latest
          # quay.io/<>/breezewiki:latest
