name: BreezeWiki - Build & Push

on:
  push:
    branches:
      - "master"
    paths:
      - "breezewiki/**"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘·â€â™€ï¸ Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ğŸ¯ Check Out Repo
        uses: actions/checkout@v2

      - name: ğŸ™ Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ‹Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ‘·â€â™‚ï¸ğŸ‹ğŸ‘·â€â™€ï¸ Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: breezewiki/.
          file: docker/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x
          labels: |
            org.opencontainers.image.source=https://github.com/Zottelchen/docker-container
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.description=BreezeWiki is a simple wiki front written in Racket.
          push: true
          cache-from: gha
          cache-to: gha
          tags: |
            zottelchen/breezewiki:latest
            ghcr.io/Zottelchen/breezewiki:latest
          # quay.io/<>/breezewiki:latest
